// @ts-nocheck — patched by scripts/patch-api-client.ts
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Composable, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAccountApikeysByApiKeyIdData, DeleteAccountApikeysByApiKeyIdError, DeleteAccountApikeysByApiKeyIdResponse, DeleteAccountData, DeleteAccountError, DeleteAccountResponse, DeleteAdminUsersByUserIdData, DeleteAdminUsersByUserIdError, DeleteAdminUsersByUserIdResponse, GetAccountApikeysByApiKeyIdData, GetAccountApikeysByApiKeyIdError, GetAccountApikeysByApiKeyIdResponse, GetAccountApikeysData, GetAccountApikeysResponse, GetAccountData, GetAccountError, GetAccountPreferencesData, GetAccountPreferencesOnboardingData, GetAccountPreferencesOnboardingResponse, GetAccountPreferencesResponse, GetAccountResponse, GetAdminUsersByUserIdData, GetAdminUsersByUserIdError, GetAdminUsersByUserIdResponse, GetAdminUsersData, GetAdminUsersError, GetAdminUsersResponse, GetAuthSessionData, GetAuthSessionError, GetAuthSessionResponse, PostAccountApikeysData, PostAccountApikeysError, PostAccountApikeysResponse, PostAdminUsersData, PostAdminUsersError, PostAdminUsersResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthResetPasswordData, PostAuthResetPasswordError, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestError, PostAuthResetPasswordRequestResponse, PostAuthResetPasswordResponse, PutAccountData, PutAccountError, PutAccountPasswordData, PutAccountPasswordError, PutAccountPasswordResponse, PutAccountPreferencesOnboardingData, PutAccountPreferencesOnboardingError, PutAccountPreferencesOnboardingResponse, PutAccountResponse, PutAdminUsersByUserIdData, PutAdminUsersByUserIdError, PutAdminUsersByUserIdPasswordData, PutAdminUsersByUserIdPasswordError, PutAdminUsersByUserIdPasswordResponse, PutAdminUsersByUserIdResponse } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>): RequestResult<TComposable, PostAuthLoginResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <TComposable extends Composable = '$fetch', DefaultT extends GetAuthSessionResponse = GetAuthSessionResponse>(options: Options<TComposable, GetAuthSessionData, GetAuthSessionResponse, DefaultT>): RequestResult<TComposable, GetAuthSessionResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAuthSessionResponse | DefaultT, GetAuthSessionError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * User Logout
 *
 * Invalidate the current user's session
 */
export const postAuthLogout = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLogoutResponse = PostAuthLogoutResponse>(options: Options<TComposable, PostAuthLogoutData, PostAuthLogoutResponse, DefaultT>): RequestResult<TComposable, PostAuthLogoutResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAuthLogoutResponse | DefaultT, PostAuthLogoutError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Reset your password using a reset token
 *
 * Reset your password using a valid reset token
 */
export const postAuthResetPassword = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordResponse = PostAuthResetPasswordResponse>(options: Options<TComposable, PostAuthResetPasswordData, PostAuthResetPasswordResponse, DefaultT>): RequestResult<TComposable, PostAuthResetPasswordResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAuthResetPasswordResponse | DefaultT, PostAuthResetPasswordError, DefaultT>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request Password Reset
 *
 * Request a password reset for a user using their username
 */
export const postAuthResetPasswordRequest = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthResetPasswordRequestResponse = PostAuthResetPasswordRequestResponse>(options: Options<TComposable, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestResponse, DefaultT>): RequestResult<TComposable, PostAuthResetPasswordRequestResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAuthResetPasswordRequestResponse | DefaultT, PostAuthResetPasswordRequestError, DefaultT>({
    url: '/auth/reset-password/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete account
 *
 * Permanently delete the authenticated user's account.
 */
export const deleteAccount = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountResponse = DeleteAccountResponse>(options: Options<TComposable, DeleteAccountData, DeleteAccountResponse, DefaultT>): RequestResult<TComposable, DeleteAccountResponse | DefaultT, DefaultT> => (options.client ?? client).delete<TComposable, DeleteAccountResponse | DefaultT, DeleteAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Get account information
 *
 * Retrieve information about the authenticated user's account.
 */
export const getAccount = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountResponse = GetAccountResponse>(options: Options<TComposable, GetAccountData, GetAccountResponse, DefaultT>): RequestResult<TComposable, GetAccountResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAccountResponse | DefaultT, GetAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Update account information
 *
 * Update information about the authenticated user's account.
 */
export const putAccount = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountResponse = PutAccountResponse>(options: Options<TComposable, PutAccountData, PutAccountResponse, DefaultT>): RequestResult<TComposable, PutAccountResponse | DefaultT, DefaultT> => (options.client ?? client).put<TComposable, PutAccountResponse | DefaultT, PutAccountError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change account password
 *
 * Change the password of the authenticated user's account.
 */
export const putAccountPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountPasswordResponse = PutAccountPasswordResponse>(options: Options<TComposable, PutAccountPasswordData, PutAccountPasswordResponse, DefaultT>): RequestResult<TComposable, PutAccountPasswordResponse | DefaultT, DefaultT> => (options.client ?? client).put<TComposable, PutAccountPasswordResponse | DefaultT, PutAccountPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all API keys
 *
 * Retrieve all API keys for the authenticated user's account.
 */
export const getAccountApikeys = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountApikeysResponse = GetAccountApikeysResponse>(options: Options<TComposable, GetAccountApikeysData, GetAccountApikeysResponse, DefaultT>): RequestResult<TComposable, GetAccountApikeysResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAccountApikeysResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options
});

/**
 * Create a new API key
 *
 * Create a new API key for the authenticated user's account.
 */
export const postAccountApikeys = <TComposable extends Composable = '$fetch', DefaultT extends PostAccountApikeysResponse = PostAccountApikeysResponse>(options: Options<TComposable, PostAccountApikeysData, PostAccountApikeysResponse, DefaultT>): RequestResult<TComposable, PostAccountApikeysResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAccountApikeysResponse | DefaultT, PostAccountApikeysError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an API key
 *
 * Delete an API key by its ID for the authenticated user's account.
 */
export const deleteAccountApikeysByApiKeyId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAccountApikeysByApiKeyIdResponse = DeleteAccountApikeysByApiKeyIdResponse>(options: Options<TComposable, DeleteAccountApikeysByApiKeyIdData, DeleteAccountApikeysByApiKeyIdResponse, DefaultT>): RequestResult<TComposable, DeleteAccountApikeysByApiKeyIdResponse | DefaultT, DefaultT> => (options.client ?? client).delete<TComposable, DeleteAccountApikeysByApiKeyIdResponse | DefaultT, DeleteAccountApikeysByApiKeyIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys/{apiKeyID}',
    ...options
});

/**
 * Get API key details
 *
 * Retrieve details of a specific API key by its ID for the authenticated user's account.
 */
export const getAccountApikeysByApiKeyId = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountApikeysByApiKeyIdResponse = GetAccountApikeysByApiKeyIdResponse>(options: Options<TComposable, GetAccountApikeysByApiKeyIdData, GetAccountApikeysByApiKeyIdResponse, DefaultT>): RequestResult<TComposable, GetAccountApikeysByApiKeyIdResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAccountApikeysByApiKeyIdResponse | DefaultT, GetAccountApikeysByApiKeyIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys/{apiKeyID}',
    ...options
});

/**
 * Get all preferences
 *
 * Retrieve all of the authenticated user's preferences in a single request, keyed by the same names as the per-preference routes. Preferences that were never set are returned with their defaults.
 */
export const getAccountPreferences = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountPreferencesResponse = GetAccountPreferencesResponse>(options: Options<TComposable, GetAccountPreferencesData, GetAccountPreferencesResponse, DefaultT>): RequestResult<TComposable, GetAccountPreferencesResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAccountPreferencesResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/preferences',
    ...options
});

/**
 * Get onboarding state
 *
 * Retrieve whether the authenticated user has completed the one-time, platform-wide welcome onboarding.
 */
export const getAccountPreferencesOnboarding = <TComposable extends Composable = '$fetch', DefaultT extends GetAccountPreferencesOnboardingResponse = GetAccountPreferencesOnboardingResponse>(options: Options<TComposable, GetAccountPreferencesOnboardingData, GetAccountPreferencesOnboardingResponse, DefaultT>): RequestResult<TComposable, GetAccountPreferencesOnboardingResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAccountPreferencesOnboardingResponse | DefaultT, unknown, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/preferences/onboarding',
    ...options
});

/**
 * Update onboarding state
 *
 * Set whether the authenticated user has completed the one-time, platform-wide welcome onboarding.
 */
export const putAccountPreferencesOnboarding = <TComposable extends Composable = '$fetch', DefaultT extends PutAccountPreferencesOnboardingResponse = PutAccountPreferencesOnboardingResponse>(options: Options<TComposable, PutAccountPreferencesOnboardingData, PutAccountPreferencesOnboardingResponse, DefaultT>): RequestResult<TComposable, PutAccountPreferencesOnboardingResponse | DefaultT, DefaultT> => (options.client ?? client).put<TComposable, PutAccountPreferencesOnboardingResponse | DefaultT, PutAccountPreferencesOnboardingError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/preferences/onboarding',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 *
 * Retrieve user accounts with optional role and search filters.
 */
export const getAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersResponse = GetAdminUsersResponse>(options: Options<TComposable, GetAdminUsersData, GetAdminUsersResponse, DefaultT>): RequestResult<TComposable, GetAdminUsersResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAdminUsersResponse | DefaultT, GetAdminUsersError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create user
 *
 * Provision a new user account with the desired role.
 */
export const postAdminUsers = <TComposable extends Composable = '$fetch', DefaultT extends PostAdminUsersResponse = PostAdminUsersResponse>(options: Options<TComposable, PostAdminUsersData, PostAdminUsersResponse, DefaultT>): RequestResult<TComposable, PostAdminUsersResponse | DefaultT, DefaultT> => (options.client ?? client).post<TComposable, PostAdminUsersResponse | DefaultT, PostAdminUsersError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 *
 * Permanently remove a user account and all of its associated data.
 */
export const deleteAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends DeleteAdminUsersByUserIdResponse = DeleteAdminUsersByUserIdResponse>(options: Options<TComposable, DeleteAdminUsersByUserIdData, DeleteAdminUsersByUserIdResponse, DefaultT>): RequestResult<TComposable, DeleteAdminUsersByUserIdResponse | DefaultT, DefaultT> => (options.client ?? client).delete<TComposable, DeleteAdminUsersByUserIdResponse | DefaultT, DeleteAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Get user
 *
 * Retrieve details for a specific user account.
 */
export const getAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends GetAdminUsersByUserIdResponse = GetAdminUsersByUserIdResponse>(options: Options<TComposable, GetAdminUsersByUserIdData, GetAdminUsersByUserIdResponse, DefaultT>): RequestResult<TComposable, GetAdminUsersByUserIdResponse | DefaultT, DefaultT> => (options.client ?? client).get<TComposable, GetAdminUsersByUserIdResponse | DefaultT, GetAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Modify profile fields or role for a user account.
 */
export const putAdminUsersByUserId = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersByUserIdResponse = PutAdminUsersByUserIdResponse>(options: Options<TComposable, PutAdminUsersByUserIdData, PutAdminUsersByUserIdResponse, DefaultT>): RequestResult<TComposable, PutAdminUsersByUserIdResponse | DefaultT, DefaultT> => (options.client ?? client).put<TComposable, PutAdminUsersByUserIdResponse | DefaultT, PutAdminUsersByUserIdError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 *
 * Set a new password for a user account and revoke active sessions.
 */
export const putAdminUsersByUserIdPassword = <TComposable extends Composable = '$fetch', DefaultT extends PutAdminUsersByUserIdPasswordResponse = PutAdminUsersByUserIdPasswordResponse>(options: Options<TComposable, PutAdminUsersByUserIdPasswordData, PutAdminUsersByUserIdPasswordResponse, DefaultT>): RequestResult<TComposable, PutAdminUsersByUserIdPasswordResponse | DefaultT, DefaultT> => (options.client ?? client).put<TComposable, PutAdminUsersByUserIdPasswordResponse | DefaultT, PutAdminUsersByUserIdPasswordError, DefaultT>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
