// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAccountApikeysByApiKeyIdData, DeleteAccountApikeysByApiKeyIdErrors, DeleteAccountApikeysByApiKeyIdResponses, DeleteAccountData, DeleteAccountErrors, DeleteAccountResponses, DeleteAdminUsersByUserIdData, DeleteAdminUsersByUserIdErrors, DeleteAdminUsersByUserIdResponses, GetAccountApikeysByApiKeyIdData, GetAccountApikeysByApiKeyIdErrors, GetAccountApikeysByApiKeyIdResponses, GetAccountApikeysData, GetAccountApikeysResponses, GetAccountData, GetAccountErrors, GetAccountPreferencesOnboardingData, GetAccountPreferencesOnboardingResponses, GetAccountResponses, GetAdminUsersByUserIdData, GetAdminUsersByUserIdErrors, GetAdminUsersByUserIdResponses, GetAdminUsersData, GetAdminUsersErrors, GetAdminUsersResponses, GetAuthSessionData, GetAuthSessionErrors, GetAuthSessionResponses, PostAccountApikeysData, PostAccountApikeysErrors, PostAccountApikeysResponses, PostAdminUsersData, PostAdminUsersErrors, PostAdminUsersResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthResetPasswordData, PostAuthResetPasswordErrors, PostAuthResetPasswordRequestData, PostAuthResetPasswordRequestErrors, PostAuthResetPasswordRequestResponses, PostAuthResetPasswordResponses, PutAccountData, PutAccountErrors, PutAccountPasswordData, PutAccountPasswordErrors, PutAccountPasswordResponses, PutAccountPreferencesOnboardingData, PutAccountPreferencesOnboardingErrors, PutAccountPreferencesOnboardingResponses, PutAccountResponses, PutAdminUsersByUserIdData, PutAdminUsersByUserIdErrors, PutAdminUsersByUserIdPasswordData, PutAdminUsersByUserIdPasswordErrors, PutAdminUsersByUserIdPasswordResponses, PutAdminUsersByUserIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Current Session
 *
 * Retrieve the current user's session information
 */
export const getAuthSession = <ThrowOnError extends boolean = false>(options?: Options<GetAuthSessionData, ThrowOnError>): RequestResult<GetAuthSessionResponses, GetAuthSessionErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthSessionResponses, GetAuthSessionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/session',
    ...options
});

/**
 * User Logout
 *
 * Invalidate the current user's session
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Reset your password using a reset token
 *
 * Reset your password using a valid reset token
 */
export const postAuthResetPassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthResetPasswordData, ThrowOnError>): RequestResult<PostAuthResetPasswordResponses, PostAuthResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<PostAuthResetPasswordResponses, PostAuthResetPasswordErrors, ThrowOnError>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request Password Reset
 *
 * Request a password reset for a user using their username
 */
export const postAuthResetPasswordRequest = <ThrowOnError extends boolean = false>(options: Options<PostAuthResetPasswordRequestData, ThrowOnError>): RequestResult<PostAuthResetPasswordRequestResponses, PostAuthResetPasswordRequestErrors, ThrowOnError> => (options.client ?? client).post<PostAuthResetPasswordRequestResponses, PostAuthResetPasswordRequestErrors, ThrowOnError>({
    url: '/auth/reset-password/request',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete account
 *
 * Permanently delete the authenticated user's account.
 */
export const deleteAccount = <ThrowOnError extends boolean = false>(options?: Options<DeleteAccountData, ThrowOnError>): RequestResult<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError> => (options?.client ?? client).delete<DeleteAccountResponses, DeleteAccountErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Get account information
 *
 * Retrieve information about the authenticated user's account.
 */
export const getAccount = <ThrowOnError extends boolean = false>(options?: Options<GetAccountData, ThrowOnError>): RequestResult<GetAccountResponses, GetAccountErrors, ThrowOnError> => (options?.client ?? client).get<GetAccountResponses, GetAccountErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options
});

/**
 * Update account information
 *
 * Update information about the authenticated user's account.
 */
export const putAccount = <ThrowOnError extends boolean = false>(options: Options<PutAccountData, ThrowOnError>): RequestResult<PutAccountResponses, PutAccountErrors, ThrowOnError> => (options.client ?? client).put<PutAccountResponses, PutAccountErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change account password
 *
 * Change the password of the authenticated user's account.
 */
export const putAccountPassword = <ThrowOnError extends boolean = false>(options: Options<PutAccountPasswordData, ThrowOnError>): RequestResult<PutAccountPasswordResponses, PutAccountPasswordErrors, ThrowOnError> => (options.client ?? client).put<PutAccountPasswordResponses, PutAccountPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all API keys
 *
 * Retrieve all API keys for the authenticated user's account.
 */
export const getAccountApikeys = <ThrowOnError extends boolean = false>(options?: Options<GetAccountApikeysData, ThrowOnError>): RequestResult<GetAccountApikeysResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAccountApikeysResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options
});

/**
 * Create a new API key
 *
 * Create a new API key for the authenticated user's account.
 */
export const postAccountApikeys = <ThrowOnError extends boolean = false>(options: Options<PostAccountApikeysData, ThrowOnError>): RequestResult<PostAccountApikeysResponses, PostAccountApikeysErrors, ThrowOnError> => (options.client ?? client).post<PostAccountApikeysResponses, PostAccountApikeysErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an API key
 *
 * Delete an API key by its ID for the authenticated user's account.
 */
export const deleteAccountApikeysByApiKeyId = <ThrowOnError extends boolean = false>(options: Options<DeleteAccountApikeysByApiKeyIdData, ThrowOnError>): RequestResult<DeleteAccountApikeysByApiKeyIdResponses, DeleteAccountApikeysByApiKeyIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAccountApikeysByApiKeyIdResponses, DeleteAccountApikeysByApiKeyIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys/{apiKeyID}',
    ...options
});

/**
 * Get API key details
 *
 * Retrieve details of a specific API key by its ID for the authenticated user's account.
 */
export const getAccountApikeysByApiKeyId = <ThrowOnError extends boolean = false>(options: Options<GetAccountApikeysByApiKeyIdData, ThrowOnError>): RequestResult<GetAccountApikeysByApiKeyIdResponses, GetAccountApikeysByApiKeyIdErrors, ThrowOnError> => (options.client ?? client).get<GetAccountApikeysByApiKeyIdResponses, GetAccountApikeysByApiKeyIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/apikeys/{apiKeyID}',
    ...options
});

/**
 * Get onboarding state
 *
 * Retrieve whether the authenticated user has completed the one-time, platform-wide welcome onboarding.
 */
export const getAccountPreferencesOnboarding = <ThrowOnError extends boolean = false>(options?: Options<GetAccountPreferencesOnboardingData, ThrowOnError>): RequestResult<GetAccountPreferencesOnboardingResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAccountPreferencesOnboardingResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/preferences/onboarding',
    ...options
});

/**
 * Update onboarding state
 *
 * Set whether the authenticated user has completed the one-time, platform-wide welcome onboarding.
 */
export const putAccountPreferencesOnboarding = <ThrowOnError extends boolean = false>(options: Options<PutAccountPreferencesOnboardingData, ThrowOnError>): RequestResult<PutAccountPreferencesOnboardingResponses, PutAccountPreferencesOnboardingErrors, ThrowOnError> => (options.client ?? client).put<PutAccountPreferencesOnboardingResponses, PutAccountPreferencesOnboardingErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/account/preferences/onboarding',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 *
 * Retrieve user accounts with optional role and search filters.
 */
export const getAdminUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAdminUsersData, ThrowOnError>): RequestResult<GetAdminUsersResponses, GetAdminUsersErrors, ThrowOnError> => (options?.client ?? client).get<GetAdminUsersResponses, GetAdminUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options
});

/**
 * Create user
 *
 * Provision a new user account with the desired role.
 */
export const postAdminUsers = <ThrowOnError extends boolean = false>(options: Options<PostAdminUsersData, ThrowOnError>): RequestResult<PostAdminUsersResponses, PostAdminUsersErrors, ThrowOnError> => (options.client ?? client).post<PostAdminUsersResponses, PostAdminUsersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 *
 * Permanently remove a user account and all of its associated data.
 */
export const deleteAdminUsersByUserId = <ThrowOnError extends boolean = false>(options: Options<DeleteAdminUsersByUserIdData, ThrowOnError>): RequestResult<DeleteAdminUsersByUserIdResponses, DeleteAdminUsersByUserIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAdminUsersByUserIdResponses, DeleteAdminUsersByUserIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Get user
 *
 * Retrieve details for a specific user account.
 */
export const getAdminUsersByUserId = <ThrowOnError extends boolean = false>(options: Options<GetAdminUsersByUserIdData, ThrowOnError>): RequestResult<GetAdminUsersByUserIdResponses, GetAdminUsersByUserIdErrors, ThrowOnError> => (options.client ?? client).get<GetAdminUsersByUserIdResponses, GetAdminUsersByUserIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Modify profile fields or role for a user account.
 */
export const putAdminUsersByUserId = <ThrowOnError extends boolean = false>(options: Options<PutAdminUsersByUserIdData, ThrowOnError>): RequestResult<PutAdminUsersByUserIdResponses, PutAdminUsersByUserIdErrors, ThrowOnError> => (options.client ?? client).put<PutAdminUsersByUserIdResponses, PutAdminUsersByUserIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 *
 * Set a new password for a user account and revoke active sessions.
 */
export const putAdminUsersByUserIdPassword = <ThrowOnError extends boolean = false>(options: Options<PutAdminUsersByUserIdPasswordData, ThrowOnError>): RequestResult<PutAdminUsersByUserIdPasswordResponses, PutAdminUsersByUserIdPasswordErrors, ThrowOnError> => (options.client ?? client).put<PutAdminUsersByUserIdPasswordResponses, PutAdminUsersByUserIdPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/admin/users/{userId}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
